django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    url(r'^_ah/warmup$', 'djangoappengine.views.warmup'),

    url(r'^$', 'main.views.home', name='home'),
    url(r'^orphans/$', 'main.views.orphans', name='orphans'),
    url(r'^flagged/$', 'main.views.flagged', name='flagged'),
    url(r'^about/$', 'main.views.about', name='about'),

    url(r'^search/$', direct_to_template, {'template': 'search.html'}, name='search'),

    url(r'^cron/changelist/$', 'main.views.cron_changelist', name='cron_changelist'),

    url(r'^ajax/rel/(\d+)/$', 'main.views.ajax_rel', name='ajax_rel'),
    url(r'^ajax/rel/(\d+)/json/$', 'main.views.ajax_rel_json', name='ajax_rel_json'),
    url(r'^ajax/node/(\d+)/$', 'main.views.ajax_node', name='ajax_node'),
    url(r'^ajax/node/(\d+)/json/$', 'main.views.ajax_node_json', name='ajax_node_json'),
    url(r'^ajax/search/$', 'main.views.ajax_search', name='ajax_search'),

    url(r'^changelist/$', 'main.views.changelist', name='changelist'),
    url(r'^add/$', 'main.views.add_node', name='add'),
    url(r'^unpin/(\d+)/$', 'main.views.unpin_node', name='unpin'),
    url(r'^invert/(\d+)/$', 'main.views.invert', name='invert'),
    url(r'^node/(\d+)/$', 'main.views.node', name='node'),
    url(r'^node/(\d+)/edit/$', 'main.views.edit_node', name='edit'),
    url(r'^node/(\d+)/delete/$', 'main.views.delete_node', name='delete'),
    url(r'^node/(\d+)/unpin/(\d+)/(\d+)/$', 'main.views.unpin_node', name='unpin'),
    url(r'^node/(\d+)/pin/$', 'main.views.pin_node', name='pin'),
    url(r'^node/(\d+)/pin/(\d+)/$', 'main.views.pin_existing', name='pin_existing'),
    url(r'^node/(\d+)/pro/$', 'main.views.add_pro', name='pro'),
    url(r'^node/(\d+)/con/$', 'main.views.add_con', name='con'),
    url(r'^node/(\d+)/premise/$', 'main.views.add_premise', name='premise'),

)

django/db/models/base.py
import types
import sys
from itertools import izip

import django.db.models.manager     # Imported to register signal handler.
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned, FieldError, ValidationError, NON_FIELD_ERRORS
from django.core import validators
from django.db.models.fields import AutoField, FieldDoesNotExist
from django.db.models.fields.related import (OneToOneRel, ManyToOneRel,
    OneToOneField, add_lazy_relation)
from django.db.models.query import Q
from django.db.models.query_utils import DeferredAttribute
from django.db.models.deletion import Collector
from django.db.models.options import Options
from django.db import (connections, router, transaction, DatabaseError,
    DEFAULT_DB_ALIAS)
from django.db.models import signals
from django.db.models.loading import register_models, get_model
from django.utils.translation import ugettext_lazy as _
import django.utils.copycompat as copy
from django.utils.functional import curry, update_wrapper
from django.utils.encoding import smart_str, force_unicode
from django.utils.text import get_text_list, capfirst
from django.conf import settings

class ModelBase(type):
    """
    Metaclass for all models.
    """
    def __new__(cls, name, bases, attrs):
        super_new = super(ModelBase, cls).__new__
        parents = [b for b in bases if isinstance(b, ModelBase)]
        if not parents:
            # If this isn't a subclass of Model, don't do anything special.
            return super_new(cls, name, bases, attrs)

        # Create the class.
        module = attrs.pop('__module__')
        new_class = super_new(cls, name, bases, {'__module__': module})
        attr_meta = attrs.pop('Meta', None)
        abstract = getattr(attr_meta, 'abstract', False)
        if not attr_meta:
            meta = getattr(new_class, 'Meta', None)
        else:
            meta = attr_meta
        base_meta = getattr(new_class, '_meta', None)

        if getattr(meta, 'app_label', None) is None:
            # Figure out the app_label by looking one level up.
            # For 'django.contrib.sites.models', this would be 'sites'.
            model_module = sys.modules[new_class.__module__]
            kwargs = {"app_label": model_module.__name__.split('.')[-2]}
        else:
            kwargs = {}

        new_class.add_to_class('_meta', Options(meta, **kwargs))
        if not abstract:
            new_class.add_to_class('DoesNotExist', subclass_exception('DoesNotExist',
                    tuple(x.DoesNotExist
                            for x in parents if hasattr(x, '_meta') and not x._meta.abstract)
                                    or (ObjectDoesNotExist,), module))
            new_class.add_to_class('MultipleObjectsReturned', subclass_exception('MultipleObjectsReturned',
                    tuple(x.MultipleObjectsReturned
                            for x in parents if hasattr(x, '_meta') and not x._meta.abstract)
                                    or (MultipleObjectsReturned,), module))
            if base_meta and not base_meta.abstract:
                # Non-abstract child classes inherit some attributes from their
                # non-abstract parent (unless an ABC comes before it in the
                # method resolution order).
                if not hasattr(meta, 'ordering'):
                    new_class._meta.ordering = base_meta.ordering
                if not hasattr(meta, 'get_latest_by'):
                    new_class._meta.get_latest_by = base_meta.get_latest_by

        is_proxy = new_class._meta.proxy

        if getattr(new_class, '_default_manager', None):
            if not is_proxy:
                # Multi-table inheritance doesn't inherit default manager from
                # parents.
                new_class._default_manager = None
                new_class._base_manager = None
            else:
                # Proxy classes do inherit parent's default manager, if none is
                # set explicitly.
                new_class._default_manager = new_class._default_manager._copy_to_model(new_class)
                new_class._base_manager = new_class._base_manager._copy_to_model(new_class)

        # Bail out early if we have already created this class.
        m = get_model(new_class._meta.app_label, name, False)
        if m is not None:
            return m

        # Add all attributes to the class.
        for obj_name, obj in attrs.items():
            new_class.add_to_class(obj_name, obj)

        # All the fields of any type declared on this model
        new_fields = new_class._meta.local_fields + \
                     new_class._meta.local_many_to_many + \
                     new_class._meta.virtual_fields
        field_names = set([f.name for f in new_fields])

        # Basic setup for proxy models.
        if is_proxy:
            base = None
            for parent in [cls for cls in parents if hasattr(cls, '_meta')]:
                if parent._meta.abstract:
                    if parent._meta.fields:
                        raise TypeError("Abstract base class containing model fields not permitted for proxy model '%s'." % name)
                    else:
                        continue
                if base is not None:
                    raise TypeError("Proxy model '%s' has more than one non-abstract model base class." % name)
                else:
                    base = parent
            if base is None:
                    raise TypeError("Proxy model '%s' has no non-abstract model base class." % name)
            if (new_class._meta.local_fields or
                    new_class._meta.local_many_to_many):
                raise FieldError("Proxy model '%s' contains model fields." % name)
            while base._meta.proxy:
                base = base._meta.proxy_for_model
            new_class._meta.setup_proxy(base)

        # Do the appropriate setup for any model parents.
        o2o_map = dict([(f.rel.to, f) for f in new_class._meta.local_fields
                if isinstance(f, OneToOneField)])

        for base in parents:
            original_base = base
            if not hasattr(base, '_meta'):
                # Things without _meta aren't functional models, so they're
                # uninteresting parents.
                continue

            parent_fields = base._meta.local_fields + base._meta.local_many_to_many
            # Check for clashes between locally declared fields and those
            # on the base classes (we cannot handle shadowed fields at the
            # moment).
            for field in parent_fields:
                if field.name in field_names:
                    raise FieldError('Local field %r in class %r clashes '
                                     'with field of similar name from '
                                     'base class %r' %
                                        (field.name, name, base.__name__))
            if not base._meta.abstract:
                # Concrete classes...
                while base._meta.proxy:
                    # Skip over a proxy class to the "real" base it proxies.
                    base = base._meta.proxy_for_model
                if base in o2o_map:
                    field = o2o_map[base]
                elif not is_proxy:
                    attr_name = '%s_ptr' % base._meta.module_name
                    field = OneToOneField(base, name=attr_name,
                            auto_created=True, parent_link=True)
                    new_class.add_to_class(attr_name, field)
                else:
                    field = None
                new_class._meta.parents[base] = field
            else:
                # .. and abstract ones.
                for field in parent_fields:
                    new_class.add_to_class(field.name, copy.deepcopy(field))

                # Pass any non-abstract parent classes onto child.
                new_class._meta.parents.update(base._meta.parents)

            # Inherit managers from the abstract base classes.
            new_class.copy_managers(base._meta.abstract_managers)

            # Proxy models inherit the non-abstract managers from their base,
            # unless they have redefined any of them.
            if is_proxy:
                new_class.copy_managers(original_base._meta.concrete_managers)

            # Inherit virtual fields (like GenericForeignKey) from the parent
            # class
            for field in base._meta.virtual_fields:
                if base._meta.abstract and field.name in field_names:
                    raise FieldError('Local field %r in class %r clashes '\
                                     'with field of similar name from '\
                                     'abstract base class %r' % \
                                        (field.name, name, base.__name__))
                new_class.add_to_class(field.name, copy.deepcopy(field))

        if abstract:
            # Abstract base models can't be instantiated and don't appear in
            # the list of models for an app. We do the final setup for them a
            # little differently from normal models.
            attr_meta.abstract = False
            new_class.Meta = attr_meta
            return new_class

        new_class._prepare()
        register_models(new_class._meta.app_label, new_class)

        # Because of the way imports happen (recursively), we may or may not be
        # the first time this model tries to register with the framework. There
        # should only be one class for each model, so we always return the
        # registered version.
        return get_model(new_class._meta.app_label, name, False)

    def copy_managers(cls, base_managers):
        # This is in-place sorting of an Options attribute, but that's fine.
        base_managers.sort()
        for _, mgr_name, manager in base_managers:
            val = getattr(cls, mgr_name, None)
            if not val or val is manager:

main/models.py
from django.db import models
from richtext.fields import AdminRichTextField

class TruthNode(models.Model):
    title = models.CharField(max_length=200, db_index=True,
        verbose_name="Claim")
    content = AdminRichTextField(max_length=20000, blank=True, 
        verbose_name="Explanation")
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title
    
class NodeRelationship(models.Model):
    PRO, CON, PREMISE = range(3)
    RELATIONSHIP_CHOICES = (
        (PRO, u'Pro'),
        (CON, u'Con'),
        (PREMISE, u'Premise'),
    )
    parent_node = models.ForeignKey(TruthNode,
        related_name="noderelationship_parent_set")
    child_node = models.ForeignKey(TruthNode,
        related_name="noderelationship_child_set")
    # child's relationship to parent
    relationship = models.IntegerField(choices=RELATIONSHIP_CHOICES)

    # if True, child has an inverse relationship with parent
    invert_child = models.BooleanField(default=False)

    # the meta-node to discuss whether this relationship is good
    discussion_node = models.ForeignKey(TruthNode, null=True, blank=True,
        related_name="noderelationship_discussion_set")

class ChangeNotification(models.Model):
    PIN, UNPIN, CREATE, DELETE, EDIT, ADD = range(6)
    NOTIFICATION_CHOICES = (
        # <user> pinned <node> as a <pin_type> to <parent>
        (PIN, u'Pin'),
        # <user> unpinned <node> as a <pin_type> from <parent>
        (UNPIN, u'Unpin'),
        # <user> created <node>
        (CREATE, u'Create'),
        # <user> deleted <node_title>
        (DELETE, u'Delete'),
        # <user> edited <node>
        (EDIT, u'Edit'),
        # <user> added <node> as a <pin_type> to <parent>
        (ADD, u'Add'),
    )
    # when the change occurred
    date = models.DateTimeField(auto_now_add=True, db_index=True)
    # which kind of notification
    change_type = models.IntegerField(choices=NOTIFICATION_CHOICES)
    # person who caused the change
    user = models.CharField(max_length=100, blank=True, null=True)
    # target node / child node
    node = models.ForeignKey(TruthNode, blank=True, null=True, 
        related_name="changenotification_node_set")
    node_title = models.CharField(max_length=200, blank=True, null=True)
    # target node 2 / parent node
    parent_node = models.ForeignKey(TruthNode, blank=True, null=True,
        related_name="changenotification_parent_node_set")
    parent_node_title = models.CharField(max_length=200, blank=True, null=True)
    pin_type = models.IntegerField(choices=NodeRelationship.RELATIONSHIP_CHOICES, blank=True, null=True)
    
class User(models.Model):
    INACTIVE, ACTIVE, BANNED = range(3)
    STATUS_CHOICES = (
        (INACTIVE, 'Registered'),
        (ACTIVE, 'Active'),
        (BANNED, 'Banned'),
    )
    email = models.EmailField(db_index=True)
    activate_code = models.CharField(max_length=100)
    status = models.IntegerField(choices=STATUS_CHOICES, default=INACTIVE)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block title %}Truth Finder{% endblock %}</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/node_dropdown.js"></script>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.9.0/build/base/base-min.css" />
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/base.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    {% block extra_head %}{% endblock %}
  </head>
  <body{% block bodytags %}{% endblock %}>
    <div id="header">
      <div id="account">
        {% if user %}
          {{ user.email }} <a href="{{ logout_url }}">Sign out</a>
        {% else %}
          <a href="{{ login_url }}">Sign in</a>
        {% endif %}
      </div>
      <div id="nav">
        <a href="{% url add %}">Add New Claim</a>
        <a href="{% url orphans %}">Orphans</a>
        <a href="{% url flagged %}">Flagged</a>
        <a href="{% url changelist %}">Changelist</a>
        <a href="{% url about %}">About</a>
        <a href="{% url search %}">Search</a>
      </div>
      <div id="logo">
        <a href="{% url home %}"><img alt="Truth Finder" src="{{ MEDIA_URL }}img/logo.png" /></a>
      </div>
    </div>
    <div id="content">
      {% block content %}{% endblock %} 
    </div>
  </body>
</html>

templates/changelist.html
{% extends 'base.html' %}

{% load hash_filter %}

{% block title %}Changelist - {{ block.super }}{% endblock %}

{% block content %}
  <h1>Changelist</h1>
  {% if changes.object_list %}
    <table class="changelist">
      {% for change in changes.object_list %}
        <tr>
          <td class="date">
            {{ change.date|date:"F d, Y H:i:s" }}
          </td>
          <td>
            {{ change.user }}
            {% if change.change_type == 0 %}
              pinned
              {% include 'changelist_node.html' %}
              as a
              <strong>{{ change.pin_type|hash:pin_type_names }}</strong>
              to
              {% include 'changelist_parent_node.html' %}
            {% endif %}{% if change.change_type == 1 %}
              unpinned
              {% include 'changelist_node.html' %}
              as a
              <strong>{{ change.pin_type|hash:pin_type_names }}</strong>
              from
              {% include 'changelist_parent_node.html' %}
            {% endif %}{% if change.change_type == 2 %}
              created
              {% include 'changelist_node.html' %}.
            {% endif %}{% if change.change_type == 3 %}
              deleted
              <em>{{ change.node_title|expand_node_links }}</em>
            {% endif %}{% if change.change_type == 4 %}
              edited
              {% include 'changelist_node.html' %}.
            {% endif %}{% if change.change_type == 5 %}
              added
              {% include 'changelist_node.html' %}
              as a
              <strong>{{ change.pin_type|hash:pin_type_names }}</strong>
              to
              {% include 'changelist_parent_node.html' %}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </table>
    <div class="pagination">
      <span class="step-links">
        {% if changes.has_previous %}
            <a href="?page={{ changes.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ changes.number }} of {{ changes.paginator.num_pages }}.
        </span>

        {% if changes.has_next %}
            <a href="?page={{ changes.next_page_number }}">next</a>
        {% endif %}
      </span>
    </div>
  {% else %}
    <p>No changes in database.</p>
  {% endif %}
{% endblock %}

templates/changelist_node.html
{% load hash_filter %}

{% if change.node.id %}
<em><a href="{% url node change.node.id %}">{{ change.node_title|expand_node_titles }}</a></em>
{% else %}
<em>{{ change.node_title|expand_node_links }}</em>
{% endif %}

templates/changelist_parent_node.html
{% load hash_filter %}

{% if change.parent_node.id %}
<em><a href="{% url node change.parent_node.id %}">{{ change.parent_node_title|expand_node_titles }}</a></em>.
{% else %}
<em>{{ change.parent_node_title|expand_node_links }}</em>.
{% endif %}

templates/delete.html
{% extends 'base.html' %}

{% load hash_filter %}

{% block title %}Deleting node - {{ block.super }}{% endblock %}

{% block content %} 
  <h1>Deleting node</h1>
  <p>
    You are about to:
  </p>
  <ul>
    <li>delete <em>{{ node.title|expand_node_links }}</em>.</li>
    {% if parent_rels %}
      <li>
        unpin from all parents:
        <ul>
          {% for parent_rel in parent_rels %}
            <li>
              <strong>{{ parent_rel.relationship|hash:rel_types }}</strong> for <em>{{ parent_rel.parent_node.title|expand_node_links }}</em>
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}
    {% if child_rels %}
      <li>
        unpin all children:
        <ul>
          {% for child_rel in child_rels %}
            <li>
              <em>{{ child_rel.child_node.title|expand_node_links }}</em> (<strong>{{ child_rel.relationship|hash:rel_types }}</strong>)
            </li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}
  </ul>
  <form action="." method="post">
    <input type="submit" value="Delete it" />
  </form>
{% endblock %}

templates/expandable_node.html
{% load hash_filter %}

<div class="node{% if node_rel.invert_child %} inverted{% endif %}">
  <div class="node-header">
    <h2>
      {% if node %}
        <a
          {% if node_rel %}
            data-relid="{{ node_rel.id }}"
          {% endif %}
          data-nodeid="{{ node.id }}"
          href="{% url node node.id %}">{% if node_rel.invert_child %}<strong>Not (</strong>{% endif %}{{ node.title|expand_node_titles }}{% if node_rel.invert_child %}<strong>)</strong>{% endif %}
        </a>
      {% else %}
        Error
      {% endif %}
    </h2>
  </div>
  <div class="node-content" style="display: none;">
  </div>
</div>

templates/flagged.html
{% extends 'home.html' %}

{% block title %}Flagged Claims - {{ block.super }}{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Debates</h2>
  {% if node_rels %}
    {% for node_rel in node_rels %}
      {% with node_rel.child_node as node %}
        {% include 'expandable_node.html' %}
      {% endwith %}
    {% endfor %}
  {% else %}
    <p>No debates here.</p>
  {% endif %}
{% endblock %}

templates/node_content.html
{% load hash_filter %}

<div class="tools">
  <a href="{% url node node.id %}">Link</a>
  <a href="{% url edit node.id %}">Edit</a>
  <a href="{% url delete node.id %}">Delete</a>
  <a href="{% url pin node.id %}">Pin</a>
  {% if node_rel %}
    <a href="{% url unpin node_rel.id %}">Unpin</a>
    <a href="{% url invert node_rel.id %}">Invert</a>
    {% if node_rel.discussion_node %}
      <a href="{% url node node_rel.discussion_node.id %}">Discuss</a>
    {% endif %}
  {% endif %}
  {% if parent_rels %}
    Parents: 
    {% for parent_rel in parent_rels %}
      <a href="{% url node parent_rel.parent_node.id %}">{{ parent_rel.parent_node.title|expand_node_titles }} ({% if parent_rel.invert_child %}Inverted {% endif %}{{ parent_rel.relationship|hash:relationship_choices }})</a>
    {% endfor %}
  {% endif %}
</div>
<div class="premise">
  {% if premise_rels %}
    <h3>Premises</h3>
    {% for premise_rel in premise_rels %}
      {% with premise_rel as node_rel %}
        {% with node_rel.child_node as node %}
          {% include 'expandable_node.html' %}
        {% endwith %}
      {% endwith %}
    {% endfor %}
  {% endif %}
  <div class="add">
    Add Premise:
    <a href="{% url premise node.id %}" class="add">Create New</a>
    <a href="{% url pin_existing node.id 2 %}" class="add">Pin Existing</a>
  </div>
</div>
{% if node.content %}
  <h3>Explanation</h3>
  <div class="html-content">
    {{ node.content|expand_node_links|safe }}
  </div>
{% endif %}
<div class="pro">
  {% if pro_rels %}
    <h3>Arguments For</h3>
    {% for pro_rel in pro_rels %}
      {% with pro_rel as node_rel %}
        {% with node_rel.child_node as node %}
          {% include 'expandable_node.html' %}
        {% endwith %}
      {% endwith %}
    {% endfor %}
  {% endif %}
  <div class="add">
    Add Pro Argument:
    <a href="{% if node_rel.invert_child %}{% url con node.id %}{% else %}{% url pro node.id %}{% endif %}" class="add">Create New</a>
    <a href="{% if node_rel.invert_child %}{% url pin_existing node.id 1 %}{% else %}{% url pin_existing node.id 0 %}{% endif %}" class="add">Pin Existing</a>
  </div>
</div>
<div class="con">
  {% if con_rels %}
    <h3>Arguments Against</h3>
    {% for con_rel in con_rels %}
      {% with con_rel as node_rel %}
        {% with node_rel.child_node as node %}
          {% include 'expandable_node.html' %}
        {% endwith %}
      {% endwith %}
    {% endfor %}
  {% endif %}
  <div class="add">
    Add Con Argument:
    <a href="{% if node_rel.invert_child %}{% url pro node.id %}{% else %}{% url con node.id %}{% endif %}" class="add">Create New</a>
    <a href="{% if node_rel.invert_child %}{% url pin_existing node.id 0 %}{% else %}{% url pin_existing node.id 1 %}{% endif %}" class="add">Pin Existing</a>
  </div>
</div>

templates/orphans.html
{% extends 'home.html' %}

{% block title %}Orphans - {{ block.super }}{% endblock %}

templates/pin.html
{% extends 'base.html' %}

{% load hash_filter %}

{% block title %}Pinning claim - {{ block.super }}{% endblock %}

{% block content %} 
  <h1>Pinning claim</h1>
  <form action="." method="post">
    {{ form.non_field_errors }}
    <table>
      <tr>
        <td class="label">
          This claim:
        </td>
        <td>
          <em>{{ child_node.title|expand_node_links }}</em>
          <input type="hidden" name="child_node" value="{{ child_node.id }}" />
        </td>
      </tr>
      <tr>
        <td>
          <label for="id_invert_child">Inverted?</label>
        </td>
        <td>
          {{ form.invert_child.errors }}
          {{ form.invert_child }}
        </td>
      </tr>
      <tr>
        <td class="label">
          <label for="id_relationship">Is a:</label>
        </td>
        <td>
          {{ form.relationship.errors }}
          {{ form.relationship }}
        </td>
      </tr>
      <tr>
        <td class="label">
          <label for="parent_node">Of:</label>
        </td>
        <td>
          {{ form.parent_node.errors }}
          <input type="text" id="parent_node" class="nodesearch" />
        </td>
      </tr>
      <tr>
        <td class="label"></td>
        <td>
          <input type="submit" value="Pin" />
        </td>
      </tr>
    </table>
  </form>
{% endblock %}

templates/pin_existing.html
{% extends 'base.html' %}

{% load hash_filter %}

{% block title %}Pinning Claim - {{ block.super }}{% endblock %}

{% block content %} 
  <h1>Pinning Claim</h1>
  <form action="." method="post">
    {{ form.non_field_errors }}
    <table>
      <tr>
        <td class="label">
          This claim:
        </td>
        <td>
          {{ form.child_node.errors }}
          <input type="text" id="child_node" class="nodesearch" placeholder="Search names or type an ID" />
        </td>
      </tr>
      <tr>
        <td>
          <label for="id_invert_child">Inverted?</label>
        </td>
        <td>
          {{ form.invert_child.errors }}
          {{ form.invert_child }}
        </td>
      </tr>
      <tr>
        <td class="label">
          <label for="id_relationship">Is a:</label>
        </td>
        <td>
          {{ form.relationship.errors }}
          {{ form.relationship }}
        </td>
      </tr>
      <tr>
        <td class="label">
          <label for="parent_node">Of:</label>
        </td>
        <td>
          <em>{{ form.parent_node.errors }}</em>
          <em>{{ parent_node.title|expand_node_links }}</em>
          <input type="hidden" name="parent_node" value="{{ parent_node.id }}" />
        </td>
      </tr>
      <tr>
        <td class="label"></td>
        <td>
          <input type="submit" value="Pin" />
        </td>
      </tr>
    </table>
  </form>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search - {{ block.super }}{% endblock %}

{% block content %}
  <h1>Search</h1>
<p>
  Unfortunately, you can only search the beginning of the nodes, case-sensitively for now.
</p>
<form action="." method="post" onsubmit="location.href='/node/' + $('#node_hidden').val() + '/'; return false;">
  <input type="text" id="node" class="nodesearch" />
  <input type="submit" value="Go"  />
</form>

{% endblock %}

templates/unpin.html
{% extends 'base.html' %}

{% load hash_filter %}

{% block title %}Unpinning claim - {{ block.super }}{% endblock %}

{% block content %} 
  <h1>Unpinning claim</h1>
  <p>
    <em>{{ relationship.child_node.title|expand_node_links }}</em> is a
    <strong>{{ relationship.relationship|hash:relationship_choices }}</strong> of
    <em>{{ relationship.parent_node.title|expand_node_links }}</em>.
  </p>
  <form action="." method="post">
    <input type="submit" value="Unpin it" />
  </form>
{% endblock %}